esphome:
  name: center
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_pw

ota:
  password: !secret esp_api_pw

switch:
  - platform: gpio
    name: "center"
    icon: "mdi:lightbulb"
    pin: GPIO12
    restore_mode: ALWAYS_ON
