esphome:
  name: center
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_pw
  - ssid: !secret wifi_ssid2
    password: !secret wifi_pw
  reboot_timeout: 0s

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_pw
  reboot_timeout: 0s

ota:
  password: !secret esp_api_pw

switch:
  - platform: gpio
    name: "center"
    icon: "mdi:lightbulb"
    pin: GPIO12
    restore_mode: ALWAYS_ON
