esphome:
  name: kitchen_sensor
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  fast_connect: on

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_pw

ota:
  password: !secret esp_api_pw

sensor:
  - platform: adc
    pin: VCC
    name: "Battery"
    icon: "mdi:battery-charging"
    filters:
      - lambda: return x * 33;
    accuracy_decimals: true
    unit_of_measurement: "%"
    update_interval: 600s

binary_sensor:
  - platform: gpio
    name: "motion"
    pin:
      number: GPIO2
      mode: INPUT
