esphome:
  name: kitchen_sensor
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  fast_connect: on

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_pw

ota:
  password: !secret esp_api_pw

binary_sensor:
  - platform: gpio
    name: "motion"
    pin:
      number: GPIO05
      mode: INPUT

