esphome:
  name: sensor
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_pw
  reboot_timeout: 0s

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Carrier Ac"
    password: "house000"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_pw
  reboot_timeout: 0s

ota:
  password: !secret esp_api_pw

remote_transmitter:
  pin:
    number: GPIO12
  carrier_duty_percent: 50%

climate:
  - platform: carrier
    name: "Living Room AC"
    supports_heat: False
    sensor: temp_sensor

binary_sensor:
  - platform: gpio
    name: "motion"
    pin:
      number: GPIO05
      mode: INPUT

sensor:
  - platform: adc
    pin: A0
    name: "brightness"
    icon: "mdi:theme-light-dark"
    update_interval: 10s
    unit_of_measurement: "%"
    filters:
      - multiply: -500.0
      - offset: 100.0
      - lambda: |-
          if (x  < 0.0) return 0.0;
          return x;

  - platform: dht
    pin: GPIO14
    model: AM2302
    temperature:
      name: "room_temperature"
      id: temp_sensor
      filters:
        - median:
            window_size: 7
    humidity:
      name: "room_humidity"
      accuracy_decimals: 1
      filters:
        - median:
            window_size: 7
    update_interval: 10s
