esphome:
  name: sensor
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_pw
  reboot_timeout: 0s

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Carrier Ac"
    password: !secret wifi_pw

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_pw
  reboot_timeout: 0s

ota:
  password: !secret esp_api_pw

remote_transmitter:
  pin:
    number: GPIO12
  carrier_duty_percent: 50%

climate:
  - platform: carrier
    name: "Living Room AC"
    id: carrier_ac
    supports_heat: False
    sensor: temp_sensor
    threshold: 4

binary_sensor:
  - platform: gpio
    name: "motion"
    device_class: motion
    pin:
      number: GPIO05
      mode: INPUT

sensor:
  - platform: adc
    pin: A0
    name: "brightness"
    icon: "mdi:theme-light-dark"
    update_interval: 10s
    unit_of_measurement: "%"
    filters:
      - multiply: -540.0
      - offset: 50.0
      - lambda: |-
          if (x  < 0.0) return 0.0;
          return x;

  - platform: dht
    pin: GPIO14
    model: AM2302
    temperature:
      name: "room_temperature"
      id: temp_sensor
      filters:
        - median:
            window_size: 7
    humidity:
      name: "room_humidity"
      accuracy_decimals: 1
      filters:
        - median:
            window_size: 7
    update_interval: 10s

switch:
  - platform: template
    name: "Dehumidifier"
    icon: "mdi:weather-rainy"
    lambda: |-
      if (id(carrier_ac).mode == 4) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - climate.control:
          id: carrier_ac
          mode: 'DEHUMIDY'
    turn_off_action:
      - climate.control:
          id: carrier_ac
          mode: 'OFF'

  - platform: template
    name: "Cleaner"
    icon: "mdi:weather-windy"
    lambda: |-
      if (id(carrier_ac).mode == 5) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - climate.control:
          id: carrier_ac
          mode: 'CLEAN'
    turn_off_action:
      - climate.control:
          id: carrier_ac
          mode: 'OFF'
