- id: '1597471084126'
  alias: Turn off TV due to over watching
  description: Turn off TV when over watching
  trigger:
  - minutes: /1
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.on_media
    state: 'on'
  - above: '1'
    condition: numeric_state
    entity_id: sensor.watching_media
  action:
  - data: {}
    entity_id: media_player.mytv
    service: media_player.turn_off
  mode: single
- id: '1606631807429'
  alias: Enable Radio
  description: Enable Radio
  trigger:
  - platform: time
    at: 07:00
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: shell_command.enable_trans_radio
    data: {}
  mode: single
- id: '1606631908034'
  alias: Disable Radio
  description: Disable Radio
  trigger:
  - platform: time
    at: '23:00'
  condition: []
  action:
  - service: shell_command.disable_trans_radio
    data: {}
  mode: single
