- id: '1597471084126'
  alias: Turn off TV due to over watching
  description: Turn off TV when over watching
  trigger:
  - minutes: /1
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.on_media
    state: 'on'
  - above: '1'
    condition: numeric_state
    entity_id: sensor.watching_media
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    after: '6:00'
    before: '23:59'
  action:
  - data: {}
    entity_id: media_player.my_tv
    service: media_player.turn_off
  mode: single
- id: '1606631807429'
  alias: Enable Radio
  description: Enable Radio
  trigger:
  - platform: time_pattern
    minutes: /1
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    after: '6:00'
    before: '22:00'
  action:
  - service: shell_command.enable_trans_radio
    data: {}
  mode: single
- id: '1606631908034'
  alias: Disable Radio
  description: Disable Radio
  trigger:
  - platform: time
    at: '23:00'
  condition: []
  action:
  - service: shell_command.disable_trans_radio
    data: {}
  mode: single
- id: '1617375258587'
  alias: Morning Radio
  description: ''
  trigger:
  - platform: time
    at: '8:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: '6:00'
    before: '12:00'
  action:
  - service: media_player.play_media
    data:
      media_content_id: http://192.168.0.3:8080/dash/mbc.mpd
      media_content_type: music
    entity_id: media_player.my_mini
  mode: single
