- id: '1536174384148'
  alias: Light On by flic button
  trigger:
  - event_data:
      button_name: flic_80e4da727be8
      click_type: single
    event_type: flic_click
    platform: event
  condition:
  - condition: state
    entity_id: group.living_room
    state: 'off'
  action:
  - data:
      entity_id: group.living_room
    service: switch.turn_on
- id: '1536174384149'
  alias: Light Off by flic button
  trigger:
  - event_data:
      button_name: flic_80e4da727be8
      click_type: single
    event_type: flic_click
    platform: event
  condition:
  - condition: state
    entity_id: group.living_room
    state: 'on'
  action:
  - data:
      entity_id: group.living_room
    service: switch.turn_off
  - data:
      entity_id: switch.kitchen
    service: switch.turn_off
- id: '1537967583786'
  alias: Light on by motion
  trigger:
  - entity_id: binary_sensor.motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.debounce_flag
    state: 'off'
  - condition: state
    entity_id: group.living_room
    state: 'off'
  - condition: or
    conditions:
    - condition: sun
      before: sunrise
      before_offset: '+1:00:00'
    - condition: sun
      after: sunset
      after_offset: '-1:00:00'
  action:
  - data:
      entity_id: group.living_room
    service: homeassistant.turn_on
- id: '1537969783296'
  alias: Trigger debounce timer by Light off
  trigger:
  - entity_id: group.living_room
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: timer.debounce
    service: timer.start
  - data:
      entity_id: input_boolean.debounce_flag
    service: homeassistant.turn_on
- id: '1537971084328'
  alias: Trigger debounce flag by timer
  trigger:
  - event_data:
      entity_id: timer.debounce
    event_type: timer.finished
    platform: event
  condition: []
  action:
  - data:
      entity_id: input_boolean.debounce_flag
    service: homeassistant.turn_off
- id: '1537971497629'
  alias: Enable First Morning Trigger
  trigger:
  - at: '5:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: input_boolean.trigger_first_morning
    service: homeassistant.turn_on
- id: '1537971572219'
  alias: Disable First Morning Trigger
  trigger:
  - at: '12:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: input_boolean.trigger_first_morning
    service: homeassistant.turn_off
- id: '1537971931130'
  alias: First Morning Motion
  trigger:
  - entity_id: binary_sensor.motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.trigger_first_morning
    state: 'on'
  action:
  - data_template:
      entity_id: media_player.my_mini
      message: 좋은 아침이에요. {{states.weather.weather.attributes.visibility}}'
    service_template: tts.google_say
  - data:
      entity_id: input_boolean.trigger_first_morning
    service: homeassistant.turn_off
- id: '1539528812555'
  alias: Light off at night
  trigger:
  - at: 04:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.living_room
    service: homeassistant.turn_off
- id: '1558130270763'
  alias: Light on kitchen
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.kitchen
    state: 'off'
  - condition: or
    conditions:
    - condition: sun
      before: sunrise
      before_offset: '+1:00:00'
    - condition: sun
      after: sunset
      after_offset: '-2:00:00'
  action:
  - data:
      entity_id: switch.kitchen
    service: switch.turn_on
- id: '1558131434527'
  alias: Light off kitchen
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'off'
    for:
      minutes: 10
  action:
  - data:
      entity_id: switch.kitchen
    service: switch.turn_off
