homeassistant:
  # Name of the location where Home Assistant is running
  name: MY's Home Assistant
  # Location required to calculate the time the sun rises and sets
  latitude:  !secret zone_home_lati
  longitude: !secret zone_home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml
  # Customize all entities in a domain
  whitelist_external_dirs:
    - /tmp

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

lovelace:
  mode: yaml

http:
  ssl_certificate: !secret certificate
  ssl_key: !secret private_key
  base_url: !secret https_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

system_health:


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - binary_sensor
    entities:
      - sensor.ondo
      - sensor.seubdo

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# DDNS
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

# Zone
zone:
  - name: Office
    latitude:  !secret zone_office_lati
    longitude: !secret zone_office_long
    icon: mdi:office

  - name: School
    latitude:  !secret zone_school_lati
    longitude: !secret zone_school_long
    icon: mdi:school

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    language: 'ko'
    cache: false

# Media Player
media_player:
  - platform: samsungtv
    host: 192.168.0.16
    mac: 50:56:bf:50:80:7f
    name: home_un55f7100

# Binary Sensor
binary_sensor:
  - platform: flic

  - platform: template
    sensors:
      tv:
        friendly_name: "TV"
        value_template: >-
          {{ is_state('media_player.home_un55f7100', 'on') }}

# Sensor
sensor:
  - platform: filter
    name: "온도"
    entity_id: sensor.room_temperature
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2

  - platform: filter
    name: "습도"
    entity_id: sensor.room_humidity
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: 00:05
        precision: 2

  - platform: history_stats
    name: Watching TV today
    entity_id: media_player.home_un55f7100
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: cert_expiry
    host: !secret https_url
    name: "인증서"

cloud:

# For Google Home Assistant
google_assistant:
  project_id: my-s-home-control-ffd58
  exposed_domains:
    - switch
    - script
    - camera
  entity_config:
    switch.cam_restart:
      expose: false

# Flags for automation
input_boolean:
  trigger_first_morning:
    name: Waiting for first morning motion

  debounce_flag:
    name: Debounce for motion

timer:
  debounce:
    duration: '00:01:00'


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
