#sun.sun:
#  hidden: true

switch.camera:
  icon: mdi:camcorder

binary_sensor.TV:
  icon: mdi:monitor
  device_class: power

binary_sensor.flic_80e4da727be8:
  friendly_name: flic_btn
  hidden: true

binary_sensor.motion:
  device_class: motion

binary_sensor.dark:
  icon: mdi:weather-night
  device_class: light

sensor.temperature:
  icon: mdi:thermometer

sensor.humidity:
  icon: mdi:water-percent

#media_player.home_un55f7100:
#  hidden: true

media_player.my_box:
  hidden: true

sensor.dark_sky_summary:
  hidden: true

timer.debounce:
  hidden: true
