Living Room:
  entities:
    - light.window
    - light.center
    - light.table
    - light.kitchen

Sensors:
  entities:
    - sensor.temperature
    - sensor.humidity
    - binary_sensor.motion
    - sun.sun
    - binary_sensor.tv

Family:
  entities:
    - device_tracker.google_maps_hanmy75gmailcom
    - device_tracker.google_maps_115178832848292642971
    - device_tracker.google_maps_101237996651145287128
