Living Room:
  entities:
    - switch.window
    - switch.center
    - switch.table

Sensors:
  entities:
    - sensor.room_temperature
    - sensor.room_humidity
    - binary_sensor.motion
    - binary_sensor.dark
    - binary_sensor.tv

Family:
  entities:
    - device_tracker.google_maps_hanmy75gmailcom
    - device_tracker.google_maps_115178832848292642971
    - device_tracker.google_maps_101237996651145287128
