Living Room:
  entities:
    - switch.window
    - switch.center
    - switch.table

Sensors:
  entities:
    - sensor.temperature
    - sensor.humidity
    - binary_sensor.motion
    - sun.sun
    - binary_sensor.tv
