
google_maps_115178832848292642971:
  hide_if_away: false
  icon:
  mac:
  name: Joung
  picture: /local/Sangsuk.png
  track: true

google_maps_hanmy75gmailcom:
  hide_if_away: false
  icon:
  mac:
  name: MY
  picture: /local/MY.png
  track: true

google_maps_101237996651145287128:
  hide_if_away: false
  icon:
  mac:
  name: Seohee
  picture: /local/Seohee.png
  track: true
