ost:
  alias: OST
  sequence:
  - service: media_player.play_media
    data_template:
      media_content_id: '{{ states(''sensor.music_url'') }}'
      media_content_type: music
    entity_id: media_player.my_mini
  mode: single
mbc:
  alias: MBC
  sequence:
  - service: media_player.play_media
    data:
      media_content_id: http://192.168.0.3:8080/dash/mbc.mpd
      media_content_type: music
    entity_id: media_player.my_mini
  mode: single
sbs:
  alias: SBS
  sequence:
  - service: media_player.play_media
    data_template:
      media_content_id: '{{ states(''sensor.sbs_radio'') }}'
      media_content_type: music
    entity_id: media_player.my_mini
  mode: single
