pause_tv:
  alias: Pause TV
  sequence:
  - data:
      entity_id: media_player.home_un55f7100
    service: media_player.media_pause
play_tv:
  alias: Play TV
  sequence:
  - data:
      entity_id: media_player.home_un55f7100
    service: media_player.media_play
