resources:
  - url: /local/gauge-card.js?v=1
    type: js

title: MY's Home Assistant
views:
  - title: Home
    cards:
      - type: entities
        title: Living Room
        entities:
          - switch.window
          - switch.center
          - switch.table

      - type: glance
        title: Sensors
        entities:
          - sensor.temperature
          - sensor.humidity
          - binary_sensor.motion
          - sun.sun
          - binary_sensor.tv

      - type: custom:gauge-card
        entity: sensor.watching_tv_today
        title: Watching TV
        max: 10
        severity:
          green: 0
          yellow: 3
          red: 6

      - type: weather-forecast
        entity: weather.weather

  - title: Location
    cards:
      - type: entities
        title: Family
        entities:
         - device_tracker.google_maps_hanmy75gmailcom
         - device_tracker.google_maps_115178832848292642971
         - device_tracker.google_maps_101237996651145287128

      - type: map
        entities:
          - entity: device_tracker.google_maps_hanmy75gmailcom
          - entity: device_tracker.google_maps_115178832848292642971
          - entity: device_tracker.google_maps_101237996651145287128
          - zone.home

  - title: Camera
    cards:
      - type: picture-glance
        title: Room Camera
        camera_image: camera.room_camera
        entities:
        - switch.camera

  - title: Media
    cards:
      - type: media-control
        entity: media_player.my_mini
      - type: media-control
        entity: media_player.my_audio
      - type: media-control
        entity: media_player.my_kitchen

  - title: Script
    cards:
      - type: entities
        title: Automation
        entities:
          - automation.light_onoff_by_flic_button
          - automation.light_on_by_motion
          - automation.first_morning_motion
          - automation.light_off_at_night

      - type: entities
        title: Flags
        show_header_toggle: false
        entities:
          - input_boolean.debounce_flag
          - input_boolean.trigger_first_morning
