title: MY's Home Assistant
views:
  - title: Home
    cards:
      - type: glance
        title: Lights
        entities:
          - entity: switch.window
            tap_action:
              action: toggle
          - entity: switch.center
            tap_action:
              action: toggle
          - entity: switch.table
            tap_action:
              action: toggle
          - entity: switch.kitchen
            tap_action:
              action: toggle

      - type: glance
        title: Sensors
        entities:
          - sensor.ondo
          - sensor.seubdo
          - sensor.balggi

      - type: glance
        title: Etc
        entities:
          - binary_sensor.motion
          - binary_sensor.tv
          - sensor.injeungseo

      - type: gauge
        entity: sensor.watching_tv_today
        title: Watching TV
        max: 10
        severity:
          green: 0
          yellow: 3
          red: 6

  - title: Media
    cards:
      - type: media-control
        entity: media_player.my_mini
      - type: media-control
        entity: media_player.my_audio
      - type: media-control
        entity: media_player.my_kitchen

  - title: Script
    cards:
      - type: entities
        title: Automation
        entities:
          - automation.light_on_by_flic_button
          - automation.light_off_by_flic_button
          - automation.light_on_by_motion
          - automation.light_off_at_night

      - type: entities
        title: Flags
        show_header_toggle: false
        entities:
          - input_boolean.debounce_flag
          - input_boolean.trigger_first_morning
